hwi_oauth:
    firewall_name: secured_area
    resource_owners:
        github:
            type: github
            client_id: %github_client_id%
            client_secret: %github_client_secret%
            options:
                csrf: true