language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
  allow_failures:
    - php: 7.0

services:
  - redis-server
  - elasticsearch
  - rabbitmq

install:
  - sudo apt-get install wkhtmltopdf
  - wkhtmltopdf
  - which wkhtmltopdf
  - composer install

script:
  - app/console rabbitmq:consumer generate_pdf --env=test & phpunit -c app
