language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
  allow_failures:
    - php: 7.0

install:
  - composer install

before_script:
  - sudo redis-server /etc/redis/redis.conf --port 6379

script:
  - phpunit -c app
