language: php

sudo: true

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
  allow_failures:
    - php: 7.0

services:
  - redis-server
  - elasticsearch
  - rabbitmq

before_install:
    - mkdir wkhtmltopdf
    - wget http://wkhtmltopdf.googlecode.com/files/wkhtmltopdf-0.9.9-static-amd64.tar.bz2
    - tar xvjf wkhtmltopdf-0.9.9-static-amd64.tar.bz2 -C wkhtmltopdf
    - sudo mv wkhtmltopdf /usr/local/bin/
    - wkhtmltopdf
    - chmod +x /usr/local/bin/wkhtmltopdf

install:
  - composer install

before_script:
  - app/console rabbitmq:consumer generate_pdf --env=test &

script:
  - phpunit -c app