language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
  allow_failures:
    - php: 7.0

services:
  - redis-server
  - elasticsearch
  - rabbitmq

before_install:
  - echo '## Downloading wkhtmltopdf'
  - wget http://download.gna.org/wkhtmltopdf/0.12/0.12.3/wkhtmltox-0.12.3_linux-generic-amd64.tar.xz
  - tar xvjf wkhtmltox-0.12.3_linux-generic-amd64.tar.xz
  - mv wkhtmltox /usr/local/bin/wkhtmltopdf

install:
  - composer install

before_script:
  - app/console rabbitmq:consumer generate_pdf --env=test &

script:
  - phpunit -c app