language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
  allow_failures:
    - php: 7.0

services:
  - redis-server
  - elasticsearch
  - rabbitmq

install:
  - composer install

before_script:
  - app/console rabbitmq:consumer generate_pdf & pwd #test

script:
  - phpunit -c app
