Vagrant.configure(2) do |config|
  config.vm.define "app.symfony.demo.on.roids" do |app|
    
    app.vm.provider "virtualbox" do |vb, override|
      override.vm.boot_timeout = 90
      override.vm.box = "ubuntu/trusty64"
      override.vm.network "private_network", ip: "192.168.50.88"
      vb.name = 'app.symfony.demo.on.roids'
      vb.memory = 1000
      vb.cpus = 2
    end

    app.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/setup.yml"
      ansible.verbose = "v"
      ansible.inventory_path = "ansible/hosts_inventory"
      ansible.limit = "all"
      ansible.sudo = true;
    end
  end
end