# This is the main configuration file of your application. It stores all the
# common options for every execution environment ('prod', 'dev', 'test').

# To avoid creating configuration files that are too long, we first import some
# files that define the values for important parts of the Symfony application,
# such as the security component and the dependency injection services
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# These are the configuration parameters that define the application's behavior
# and which are independent from the underlying technical infrastructure
# See http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    # This parameter defines the codes of the locales (languages) enabled in the application
    app_locales: en|fr|de|es|cs|nl|ru|uk|ro|pt_BR|pl|it|ja|id|ca
    app.notifications.email_sender: anonymous@example.com

# Basic configuration for the Symfony framework features
framework:
    # Uncomment the 'ide' option to turn all of the file paths in an exception
    # page into clickable links that open the given file using your favorite IDE.
    # Supported values are 'textmate', 'macvim', 'emacs' and 'sublime' shortcuts
    # and any custom configuration string, such as: "phpstorm://open?file=%%f&line=%%l"
    # See http://symfony.com/doc/current/reference/configuration/framework.html#ide
    ide: sublime

    # esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration (used for rendering application templates)
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - "bootstrap_3_layout.html.twig"
        - "form/fields.html.twig"
    globals:
        github_client_id: %github_client_id%

# Assetic Configuration (used for managing web assets: CSS, JavaScript, Sass, etc.)
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    filters:
        cssrewrite: ~
        jsqueeze: ~
        scssphp:
            # the formatter must be the FQCN (don't use the 'compressed' value)
            formatter: "Leafo\\ScssPhp\\Formatter\\Compressed"

# Doctrine Configuration (used to access databases and manipulate their information)
doctrine:
    dbal:
        # instead of configuring the database access options in this file, we pull
        # them from the app/config/parameters.yml file. The reason is that config.yml
        # stores options that change the application behavior and parameters.yml
        # stores options that change from one server to another
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration (used to send emails)
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# KnpPaginatorBundle configuration (used to paginate large result set)
knp_paginator:
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig

jms_serializer:
    metadata:
        directories:
            AppBundle:
                namespace_prefix: "AppBundle"
                path: "%kernel.root_dir%/../src/RestBundle/Resources/config/serializer/AppBundle"

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        mime_types:
            json: ['application/json', 'application/json;version=1.0', 'application/json;version=1.1', 'application/json;version=1.2']
        view_response_listener: 'force'
        formats:
            xml:  true
            json: true
        templating_formats:
            html: true
    routing_loader:
        default_format: html
    format_listener:
        rules:
            - { path: ^/, priorities: [ html, json, xml ], fallback_format: ~, prefer_extension: true }
        media_type:
            version_regex: '/(v|version)=(?P<version>[0-9\.]+)/'
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    body_listener: true

nelmio_api_doc: ~

bazinga_rest_extra: ~

fos_http_cache:
    cache_control:
        rules:
            -
                match:
                    path: ^/api/v*
                    methods: [GET, HEAD]
                headers:
                    cache_control: { public: true, max_age: 15, s_maxage: 30 }
                    last_modified: "-1 hour"
                    vary: [Accept-Encoding, Accept-Language]
hwi_oauth:
    firewall_name: secured_area
    resource_owners:
        github:
            type: github
            client_id: %github_client_id%
            client_secret: %github_client_secret%
            options:
                csrf: true
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://localhost

fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        app:
            index_name: app_%kernel.environment%
            types:
                post:
                    mappings:
                        id: ~
                        slug:
                            boost: 3.50
                        title:
                            boost: 10.00
                        summary:
                            boost: 5.00
                        content:
                            boost: 2.50
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Post
                        provider: ~
                        listener:
                            immediate: ~
                        finder: ~

old_sound_rabbit_mq:
    connections:
        default:
            host:     'localhost'
            port:     5672
            user:     'admin'
            password: 'symfony.demo.on.roids'
            vhost:    '/'
            lazy:     false
            connection_timeout: 3
            read_write_timeout: 3

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false

            # requires php-amqplib v2.4.1+
            heartbeat: 0
    producers:
        generate_pdf:
            connection:       default
            exchange_options: {name: 'generate-pdf', type: direct}
    consumers:
        generate_pdf:
            connection:       default
            exchange_options: {name: 'generate-pdf', type: direct}
            queue_options:    {name: 'generate-pdf'}
            callback:         rabbitmq_pdf_generator_consumer

knp_snappy:
        pdf:
            enabled:    true
            binary:     /usr/local/bin/wkhtmltopdf #"\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\"" for Windows users
            options:    []
        image:
            enabled:    true
            binary:     /usr/local/bin/wkhtmltoimage #"\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltoimage.exe\"" for Windows users
            options:    []