---

dependencies: []

galaxy_info:
  author: klen
  company: Stouts
  description: Manage rabbitmq
  license: MIT
  platforms:
  - name: Ubuntu
    versions:
    - all
  categories:
  - system
  - networking
  - database:nosql
