old_sound_rabbit_mq:
    connections:
        default:
            host:     'localhost'
            port:     5672
            user:     'admin'
            password: 'symfony.demo.on.roids'
            vhost:    '/'
            lazy:     false
            connection_timeout: 3
            read_write_timeout: 3

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false

            # requires php-amqplib v2.4.1+
            heartbeat: 0
    producers:
        generate_pdf:
            connection:       default
            exchange_options: {name: 'generate-pdf_prod', type: direct}
    consumers:
        generate_pdf:
            connection:       default
            exchange_options: {name: 'generate-pdf_prod', type: direct}
            queue_options:    {name: 'generate-pdf_prod'}
            callback:         rabbitmq_pdf_generator_consumer

knp_snappy:
        pdf:
            enabled:    true
            binary:     /usr/local/bin/wkhtmltopdf #"\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\"" for Windows users
            options:    []
        image:
            enabled:    true
            binary:     /usr/local/bin/wkhtmltoimage #"\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltoimage.exe\"" for Windows users
            options:    []