fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        mime_types:
            json: ['application/json', 'application/json;version=1.0', 'application/json;version=1.1', 'application/json;version=1.2']
        view_response_listener: 'force'
        formats:
            xml:  true
            json: true
        templating_formats:
            html: true
    routing_loader:
        default_format: html
    format_listener:
        rules:
            - { path: ^/, priorities: [ html, json, xml ], fallback_format: ~, prefer_extension: true }
        media_type:
            version_regex: '/(v|version)=(?P<version>[0-9\.]+)/'
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    body_listener: true

jms_serializer:
    metadata:
        directories:
            AppBundle:
                namespace_prefix: "AppBundle"
                path: "%kernel.root_dir%/../src/RestBundle/Resources/config/serializer/AppBundle"

nelmio_api_doc: ~
fos_http_cache:
    cache_control:
        rules:
            -
                match:
                    path: ^/api/v*
                    methods: [GET, HEAD]
                headers:
                    cache_control: { public: true, max_age: 15, s_maxage: 30 }
                    last_modified: "-1 hour"
                    vary: [Accept-Encoding, Accept-Language]

bazinga_rest_extra: ~