rest_controller:
    path:     /
    type:     rest
    resource: RestBundle\Controller\RestController
    prefix: v1
    name_prefix: api_v1_

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc